CREATE DATABASE 807web;
USE 807web;

source dbscripts/create_station_tables.sql
source dbscripts/create_station_triggers.sql
source dbscripts/create_users_tables.sql
source dbscripts/create_evaluation_tables.sql
source dbscripts/create_events_tables.sql

source dbscripts/attendance/create_term_table.sql
source dbscripts/attendance/create_user_table.sql
source dbscripts/attendance/create_section_table.sql
source dbscripts/attendance/create_pepband_table.sql
source dbscripts/attendance/create_member_table.sql
source dbscripts/attendance/create_mbevent_table.sql
source dbscripts/attendance/create_eventattendance_table.sql
source dbscripts/attendance/create_createEventAndAttendance_procedure.sql
source dbscripts/attendance/create_addAttendancesForNewMembers_procedure.sql
source dbscripts/attendance/create_reassignRemainingPepEventsForMember_procedure.sql